language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "pip install setuptools"
    - "pip install pygments requests" # core dependencies
    - "pip install 'curtsies<0.2.0' greenlet" # curtsies specific dependencies
    - "pip install babel" # translation specific dependencies
    - "pip install sphinx" # documentation specific dependencies
    - "python setup.py install"

script:
    - cd build/lib/
    - "nosetests bpython/test"
