language: python
sudo: false
notifications:
  webhooks: http://ramacher.at:2810/7e210HhiKpMbF7L9/travisci

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

env:
    - RUN=nosetests
    - RUN=build_sphinx

install:
    - ./.travis.install.sh

script:
    - ./.travis.script.sh
