language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install setuptools
    # core dependencies
    - pip install pygments requests
    # curtsies specific dependencies
    - pip install 'curtsies >=0.1.15,<0.2.0' greenlet
    # translation specific dependencies
    - pip install babel
    # documentation specific dependencies
    - pip install sphinx
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
    - python setup.py install

script:
    - cd build/lib/
    - "nosetests bpython/test"
