language: python
sudo: false

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

env:
    - RUN=nosetests
    - RUN=build_sphinx

install:
    - ./.travis.install.sh

script:
    - if [[ $RUN == build_sphinx ]]; then python setup.py build_sphinx; fi
    - if [[ $RUN == build_sphinx ]]; then python setup.py build_sphinx_man; fi
    - if [[ $RUN == nosetests ]]; then cd build/lib/ && nosetests bpython/test; fi
