language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "pip install 'curtsies<0.2.0' greenlet pygments requests"
    - "python setup.py install"

script:
    - cd build/lib/
    - "nosetests bpython/test"
